// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvrSOT04pYreiLfD5X8mVnJwRSGsx5wRQ',
    appId: '1:718606030254:web:fa078e79e11d668481643f',
    messagingSenderId: '718606030254',
    projectId: 'broken-crave-notes',
    authDomain: 'broken-crave-notes.firebaseapp.com',
    storageBucket: 'broken-crave-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6gBBg9pkGd9jsI0yKQNSm2oPobw-FlI',
    appId: '1:718606030254:android:bb35c76a18f6f4ec81643f',
    messagingSenderId: '718606030254',
    projectId: 'broken-crave-notes',
    storageBucket: 'broken-crave-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRQllov5QbptMksVe-PSPQpqsSqbosPU',
    appId: '1:718606030254:ios:96310c19c0701c0881643f',
    messagingSenderId: '718606030254',
    projectId: 'broken-crave-notes',
    storageBucket: 'broken-crave-notes.appspot.com',
    iosBundleId: 'com.broken.crave.brokenNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRRQllov5QbptMksVe-PSPQpqsSqbosPU',
    appId: '1:718606030254:ios:3399bd2c633c669681643f',
    messagingSenderId: '718606030254',
    projectId: 'broken-crave-notes',
    storageBucket: 'broken-crave-notes.appspot.com',
    iosBundleId: 'com.broken.crave.brokenNotes.RunnerTests',
  );
}
